# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Suela Palushi
title: Product Manager
email: suelapalushi@protonmail.com
website: suelapalushi.tech

# Social links
twitter_username: suelapalushi
github_username:  suelap
instagram_username: suela_palushi
linkedin_username: suela-palushi-85bb4b96

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/img/me.jpg
about_content: | # this will include new lines to allow paragraphs
    Hi, my name is Suela and I am an agile practitioner with a history of working in the Open Source computer software industry. Mostly interested in Software quality assurance and product development, I am always trying to learn more about the best practices followed in the industry, especially among different open source projects, communities, and companies following an Open Source business model. I first got in touch with the Open Source movement at [Open Labs Hackerspace](https://openlabs.cc), the first community in Albania focused in promoting software freedom, open-source software, free culture, online security, and knowledge sharing. Since <mark>2014</mark> I have been actively involved with Open Labs activities.

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | #
    This is the "less boring" bit about me that most will probably still find boring. I usually enjoy long walks in the afternoon, scrolling random Reddit threads and procrastinating effectively by reading on topics I am not particularly interested in. I love sharing shower thoughts with friends who don't usually hesitate in using them against me whenever possible -- this can be quite fun from time to time. Whenever there is nothing to talk about I will talk about my cat, or how much I want a dog in my life ( now you know!).
# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
